// Barrel export — import primitives from '../components' in station props.
export { Tree, type TreeProps } from './Tree';
export { TreeModel, type TreeModelProps } from './TreeModel';
export { Bush, type BushProps } from './Bush';
export { TNT, type TNTProps } from './TNT';
export { Barrel, type BarrelProps } from './Barrel';
export { HayBale, type HayBaleProps } from './HayBale';
export { StaticBird, type StaticBirdProps } from './StaticBird';
export { Building, type BuildingProps } from './Building';
export { BlockCharacter, type BlockCharacterProps } from './BlockCharacter';
export { BoatModel } from './BoatModel';
export { ModelFigure, type ModelFigureConfig, type ModelFigureProps } from './ModelFigure';
export { Mailbox, type MailboxProps } from './Mailbox';
export { GlowingOrb, type GlowingOrbProps } from './GlowingOrb';
export { GradCap, type GradCapProps } from './GradCap';
export { Medal, type MedalProps } from './Medal';
export { Podium, type PodiumProps } from './Podium';
export { CloudPuff, type CloudPuffProps } from './CloudPuff';
export { ExploreRing, type ExploreRingProps } from './ExploreRing';
export { SchoolBuilding, type SchoolBuildingProps } from './SchoolBuilding';
export { Bench, type BenchProps } from './Bench';
export { Pencil, type PencilProps } from './Pencil';
export { BookStack, type BookStackProps } from './BookStack';
export { Ruler, type RulerProps } from './Ruler';
export { Fence, type FenceProps } from './Fence';
export { Signboard, type SignboardProps } from './Signboard';
export { resolvePosition, type PlacementProps, type AccentProps } from './types';
